### ISSUE TITLE
当识别出错时仍然创建硬链接

### ISSUE THREAD

**Issue by cornjosh** [xsm1997/animeLinker#1]
![image](https://user-images.githubusercontent.com/42884704/105541578-f2e87280-5d32-11eb-9897-76f468ee7878.png)
创建硬链接前选择n
![image](https://user-images.githubusercontent.com/42884704/105541662-0c89ba00-5d33-11eb-8ac5-654af67c52b9.png)
会在源文件夹创建名为 xxx(2).xxx 的硬链接

**Comment by xsm1997** [comment]
这个的逻辑就是这样，如果你选择了进入某一个目录，无论识别对不对，都会生成硬链接。只不过在你选择识别不对的情况下，应该是会以原本的文件名，在目标文件夹内生成硬链接。我这里这个逻辑工作正常，麻烦再尝试几次，然后提供更多信息。
我之后有时间会加入一个选项，让用户选择是否创建硬链接。

**Comment by xsm1997** [comment]
而且，我有加入防止重名导致覆盖的判断，你这个(2)应该是你文件夹内有不带括号的原本文件，为了防止覆盖，才会生成带序号的硬链接。

**Comment by cornjosh** [comment]
感谢回复！

> 而且，我有加入防止重名导致覆盖的判断，你这个(2)应该是你文件夹内有不带括号的原本文件，为了防止覆盖，才会生成带序号的硬链接。

关于这个，文件夹内没有重名文件：

![image](https://user-images.githubusercontent.com/42884704/105577306-aabd6480-5db3-11eb-83e4-111137101099.png)

运行是在 windows 下通过 SMB 访问并创建 hard link

**Comment by xsm1997** [comment]
这个结果比较奇怪，你能给我一下运行的命令吗？我尝试复现一下

**Comment by xsm1997** [comment]
试试不把源目录和目标目录设置成同一个，看看能否复现？

**Comment by cornjosh** [comment]
> 这个结果比较奇怪，你能给我一下运行的命令吗？我尝试复现一下

好的，以下

`main.exe --src "\\Tower\video\download\anime\[Snow-Raws] ReLIFE" --dst "\\Tower\video\download"`

输入 `Y` 时文件名没有问题， `N` 时会有重命名情况

**Comment by xsm1997** [comment]
已修复，这回加上了选项，请再次测试，谢谢。

**Comment by cornjosh** [comment]
已经修复了，按预期运行，谢谢
